# Generated by Django 2.2.16 on 2022-06-24 10:40

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_auto_20220624_0953'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='cant_follow_urself',
        ),
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.CheckConstraint(check=models.Q(_negated=True, user=django.db.models.expressions.F('author')), name='cant_follow_urself'),
        ),
    ]
